### ISSUE TITLE
90128

### ISSUE THREAD

**Issue by cn-Meepo** [hisan-web/flutter_face_detect#1]
请问返回错误码90128 是什么意思？官网查不到这个错误码

**Comment by hisan-web** [comment]
需要加入phone读取权限

------------------------------------------------------------------
发件人：cn-Meepo <notifications@github.com>
发送时间：2020年5月26日(星期二) 10:46
收件人：hisan-web/flutter_face_detect <flutter_face_detect@noreply.github.com>
抄　送：Subscribed <subscribed@noreply.github.com>
主　题：[hisan-web/flutter_face_detect] 90128 (#1)

请问返回错误码90128 是什么意思？官网查不到这个错误码

**Comment by hisan-web** [comment]
权限问题

**Comment by cn-Meepo** [comment]
@hisan-web 谢谢
