### ISSUE TITLE
提一个功能的小建议

### ISSUE THREAD

**Issue by fengxiaozi123** [hisan-web/flutter_face_detect#2]
你好，作者，我今天发现了你开发的这个插件，功能还挺好，就是想给你提个功能优化的小建议，看看你能不能加上，就是希望在识别实物人脸的时候可以暂停匹配，或者可以手动触发暂停匹配，并且最好是增加一个可以把图片保存的回调函数可以获得当前的图片用于后续的处理。
希望您可以考虑一下这个建议，谢谢！

**Comment by hisan-web** [comment]
这个功能是在第二点人脸比对中实现的，目前因为工作太忙，没有空闲的时间去更新，后期有时间了会更新的。
