### ISSUE TITLE
错误码：90128

### ISSUE THREAD

**Issue by au333333** [hisan-web/flutter_face_detect#3]
I/FaceMethodCall(12827): context：com.hs.face_example.MainActivity@dee1e5，appId：CjGWF7wY9uYDeKsUD8xcBdyM2Xkbc2AyjQkpc2gvFpWu，sdkKey：HKyEKmpqQB84uyj7M23bQWi4Uwto7ZLYyoui9SszrbaF
I/FaceMethodCall(12827): engine result：90128
E/FaceMethodCall(12827): Face SDK Register Error，ErrorCode： 90128
I/flutter (12827): 激活失败，错误码：90128请根据错误码查询对应错误

**Comment by hisan-web** [comment]
> I/FaceMethodCall(12827): context：com.hs.face_example.MainActivity@dee1e5，appId：CjGWF7wY9uYDeKsUD8xcBdyM2Xkbc2AyjQkpc2gvFpWu，sdkKey：HKyEKmpqQB84uyj7M23bQWi4Uwto7ZLYyoui9SszrbaF
> I/FaceMethodCall(12827): engine result：90128
> E/FaceMethodCall(12827): Face SDK Register Error，ErrorCode： 90128
> I/flutter (12827): 激活失败，错误码：90128请根据错误码查询对应错误

进官方查阅相应错误码即可。
