### ISSUE TITLE
需要人脸对比

### ISSUE THREAD

**Issue by ShanRaw** [hisan-web/flutter_face_detect#4]
大佬
需要人脸对比
可以设置相似度 是否活体 特征码对比库地址

**Comment by ShanRaw** [comment]
人脸追踪很是很流畅的。 打开页面的时候路由动画回卡顿  设置200毫秒再显示FaceDetectCameraView  路由动画正常

**Comment by ShanRaw** [comment]
准备自己尝试修改
并且把初始化放在了子线程

**Comment by FaceAISDK** [comment]
https://github.com/FaceAISDK/FaceAISDK_Flutter_Plugin
